payment.create=API to create a new payment.
payment.getById=API to get payment details by payment ID.
payment.getAll=API to get all available payments.
payment.update=API to update payment details by payment ID.
payment.delete=API to delete a payment by payment ID.